### ISSUE TITLE
respond to "hello" during the conversation differently

### ISSUE THREAD

**Issue by BenPeterson** [HUD-Digital-Services/customer-service-bot#1]
When the user gets stuck and types "hello" during conversation the bot should offer help instead of repeating "hello" 

![screen shot 2017-09-14 at 12 23 09 pm](https://user-images.githubusercontent.com/7881766/30441788-65534c8a-9948-11e7-81fc-5c9784f2130b.png)

**Comment by markbubel** [comment]
Bot now handles "hello", "hello?", and "are you there?" more gracefully when chatting. However, user must type one of these words exactly.

**Comment by BenPeterson** [comment]
Looks good! Tested it out and I think it works smooth enough for now
