### ISSUE TITLE
Add usage instructions

### ISSUE THREAD

**Issue by markbubel** [HUD-Digital-Services/customer-service-bot#5]
@BenPeterson I'm wondering if we should list steps on the page to use the bot such as step 1: say hello, step 2: make sure choice, etc?

**Comment by BenPeterson** [comment]
It already says say hello. I think it might be more effective if the bot talks first to prompt the user.

**Comment by BenPeterson** [comment]
Part of what I was trying to redesign earlier was to make the layout a little clearer with the "say hello" bolder. - If you were able to view my changes - that I made earlier then un-commited cause they looked weird - and they looked okay to you, can you try to commit them and see what you think of that layout?

**Comment by BenPeterson** [comment]
@markbubel let me know if that last comment makes sense.

**Comment by markbubel** [comment]
Big update.. bot now joins the conversation automatically once the page is loaded. It will proactively say hello and then start the `menu` dialog.

**Comment by markbubel** [comment]
About your new layout change.. I don't think I can see what you changed since you rolled back the change. It didn't look like anything changed at all on the website, so that's why I said nothing broke.

Take a look at the page now and see what you want to change. I removed the 'say hello' content because the bot now says hello automatically.
