### ISSUE TITLE
user misidentified tried to enter text in the wrong field

### ISSUE THREAD

**Issue by BenPeterson** [HUD-Digital-Services/customer-service-bot#6]
**Problem**
Just tested the bot with an FPM CSR who had her screen set so large that the field to enter text could only be seen after scrolling. She tried to write in the view window where the chat message history is viewed.

**Suggestions**
1. shorten the height of the chat message view by 1/3. so that the text field is easily screen
2. if possible, have the initial text from the bot appear at the top of the chat message view instead of the bottom.

**Comment by markbubel** [comment]
Will look into this, but I think option 2 isn't possible. Option 1 should be okay.

**Comment by BenPeterson** [comment]
I think option 1 should be fine.

**Comment by markbubel** [comment]
Shortened the height of the chat window.
